### ISSUE TITLE
Requesting for entire a20 code as a single working module

### ISSUE THREAD

**Issue by KrishnanRaghavan** [openpower-cores/a2o#12]
Hello everyone, i am requesting for anyone to share the entire a20 core as a single module and not as a individual block.

**Comment by openpowerwtf** [comment]
What do you mean by 'a2o core'?  For Vivado, the core is built as IP (c_wrapper).  You can use that version or create a new wrapper with different interface.

**Comment by KrishnanRaghavan** [comment]
To simulate the a20 core  all the  blocks mentioned  should be available as a single module for which the testbench can be created and simulated.

**Comment by openpowerwtf** [comment]
That module is created if you use Vivado - it generates the wrapper RTL for the board design.   That can be used for simulation and synthesis in Vivado, or you can take the RTL and modify it for your TB (generate your own clocks, add memory model, etc.) in any simulator.

You could also wrap just the interesting pieces in a top-level macro and have your TB handle clocks/memory/etc.

One more 😃 - you can use the AWS EC2 F1 HDK environment and create a CL/SH board design which can be simulated and implemented with their tools (it uses Vivado).   That environment has DDR, PCIE slave/master (host<->FPGA), and virtual debug available for use in your design.  It does not require an AWS instance for sim/impl.  It has useful SV and C API's for interacting with the FPGA.

**Comment by KrishnanRaghavan** [comment]
Thanks for the reply openpowerwtf .  I have another query,
Is it possible to build the  a20 core in a FPGA board consisting of ARM cortex processor(for eg: ZYNQ Ultrascale +ZCU111 FPGA Board)  to build in the PL section of the FPGA? or should we require a customized FPGA board with a20 core inbuilt?

**Comment by openpowerwtf** [comment]
I don't know of any fundamental problems you would have doing that, as long as the FGPA area is large enough.  You would set up AXI address spaces to do what you want.  I think you could also set up split AXI buses if you wanted to use them differently (like functional/debug).

If you wanted to run as a true SMP (ARM+A2O), you would need to add logic to A2L2_AXI to handle things like L1 back-invalidate.

If you are using the ARMs for a type of BMC/driver for the A2O (ARM can read/write DDR and access PL through AXI), you might want some logic on the PL AXI bus so the ARM can read/write various A2O signals like reset, threadstop, interrupts, errors, etc.

**Bonus points** for adapting something like OpenOCD to control/sample the core internals through JTAG and AXI (the logic is in the core for this through a different serial interface).

**Comment by KrishnanRaghavan** [comment]
Thanks for the reply openpower. I have a few more questions which arised when i was working on this
(1) Access to the SDK tools/documentation of A2O core with respect to Xilinx FPGA is
required.
(2) FPGA porting standard guidelines – converting the image file of the RTL, specific
switches to be enabled etc., (Xilinx specific).
(3) Support for porting OS on the A2O core.
4)Kindly the address the above issue by providing the address plan to it.

**Comment by openpowerwtf** [comment]
There isn't any SDK or other FPGA info except what's in the project build scripts and general documentation.  

Any OS that is attempted to be ported must be compatible with ISA 2.07 (and thus incompatible with current requirements).  FreeRTOS should be able to be updated from PPC4xx version (low-level stack/task handling, etc.).  Linux would have to be a contemporary level in A2I/A2O timeframe.

**Comment by KrishnanRaghavan** [comment]
Thanks for the reply openpower.
