### ISSUE TITLE
Invalid GoogleDrive URL for video doc.

### ISSUE THREAD

**Issue by cbalint13** [openpower-cores/a2o#16]
The mentioned link in `rel/doc/a2_build_video.md` is invalid.

**Comment by openpowerwtf** [comment]
Thanks - will get that fixed up once the repo is moved.  FYI - it is just showing the same steps as is listed in the readme.

**Comment by cbalint13** [comment]
> Thanks - will get that fixed up once the repo is moved. FYI - it is just showing the same steps as is listed in the readme.

* Managed it on a xcku15p following just the docs (all the readme in order described).
