### ISSUE TITLE
blank  bd after synthesis

### ISSUE THREAD

**Issue by zhanghaojia123456** [openpower-cores/a2o#3]
Hi,
Thanks for open-sourcing so great project.
After creating vivado project (.xpr file), open in vavado and synthesis, there is nothing in the design. Also, I noticed that in create_project.tcl file, many IP properties are set, but IPs and source RTL files are not added to the project. 

How to synthesize and implement the project?

Thanks,
Jerry

**Comment by shgoupf** [comment]
Please follow the steps described in https://github.com/openpower-cores/a2o/blob/master/rel/readme.md.

You need to firstly get into each IP directory, that is `build/ip_user/<xxx>`, and follow the `readme.md` in that directory. 

After you finished all the steps in the IP directories, please get into this directory: https://github.com/openpower-cores/a2o/tree/master/rel/build/bd and follow the steps described in the `readme.md`.

You might encounter some problems (missing nets) during the `ila.tcl` step depends on your vivado version. You might need to find the proper net name and change them in https://github.com/openpower-cores/a2o/tree/master/rel/build/bd/ila.tcl accordingly.

**Comment by openpowerwtf** [comment]
Thanks @shgoupf! There's also link to a short video in the doc directory showing the build (rel/doc/a2_build_video.md).

We can collect good ILA setup scripts here if anyone wants to submit them.
